articles/urls.py
from django.urls import path

from articles.views import author_details

urlpatterns = [

    path("authors/<int:author_id>/", author_details, name="author_details"),

]

books/urls.py
from django.urls import path

from .views import listview, details

app_name = "books"
urlpatterns = [

    path("books/", listview, name="list"),
    path("books/<int:book_id>", details, name="details"),

]

examples/urls.py
from django.contrib import admin
from django.urls import path, include

from books.views import listview
from posts.views import listview as postslistview
from main.views import homepage, greetings

# /greetings/

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('articles.urls')),
    path("", include("main.urls")),

    # można tak bardzo ogólnie przerzucić szukanie do innego urls
    path("", include("books.urls")),

    # można dać przedrostek - wspolny dla wszystkich wzorcow
    # z urls ktory inkludujemy
    path("posts/", include("posts.urls")),   # /posts/
    # /articles/
    # /authors/

]

main/urls.py
from django.urls import path

from .views import homepage, greetings

urlpatterns = [

    path("", homepage, name='homepage'),
    path("greetings/", greetings),

    path("greetings/<name>", greetings),
    # path("books/", greetings),

]

posts/urls.py
from django.urls import path

from .views import listview

app_name = "posts"
urlpatterns = [
    path("", listview, name="list"),  # /posts/
]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    # author = models.ForeignKey(Author, on_delete=models.CASCADE)
    author = models.ForeignKey('articles.Author', on_delete=models.CASCADE, related_name='articles')

    def __str__(self):
        return f"Article: {self.title} {self.author}"

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(null=True, blank=True)

    def __repr__(self):
        return f"Author: {self.first_name} {self.last_name}"

    def __str__(self):
        return f"Author: {self.first_name} {self.last_name}"

books/models.py
from django.db import models
from django.template.defaultfilters import slugify

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(null=True, blank=True)
    death_date = models.DateField(null=True, blank=True)

    def __repr__(self):
        return f"Author: {self.first_name} {self.last_name}"

    def __str__(self):
        return f"Author: {self.first_name} {self.last_name}"

class Book(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    # author = models.CharField(max_length=200)
    author = models.ForeignKey('books.Author', on_delete=models.CASCADE, related_name='books')
    year = models.SmallIntegerField()
    pages = models.IntegerField()
    slug = models.SlugField(null=True)


    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.slug:
            self.slug = slugify(self.title)

        return super().save(
            force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields
        )


    def __str__(self):
        return f"Book: {self.title} ({self.author})"

main/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

# Create your models here.

articles/views.py
from django.shortcuts import render

# Create your views here.
from articles.models import Author


def author_details(request, author_id):
    author = Author.objects.get(pk=author_id)
    return render(
        request=request,
        template_name="authors/details.html",
        context={'author': author}
    )

books/views.py
from django.shortcuts import render

from books.services import book_service


# books?q=cos
def listview(request):
    print(request.GET)
    q = request.GET.get("q")
    print(q)
    if q:
        books = book_service.filter(q=q)
    else:
        books = book_service.get_all_books()
    return render(
        request=request,
        template_name="books/list.html",
        context={'books': books}
    )


def details(request, book_id: int):
    book = book_service.get_book(book_id)
    return render(
        request=request,
        template_name="books/details.html",
        context={'book': book}
    )

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader

# Create your views here.


def homepage(request):
    # with open("templates/homepage.html") as f:
    #     html=f.read()

    # template = loader.get_template("homepage.html")
    # context = {"dane":[1, 2, 3]}
    # return HttpResponse(template.render(context, request))

    return render(
        request,
        "homepage.html",
        {
            "dane": "ALA MA KOTA",
            "a_list": [1, 2, 3],
            "author": {"name": "Adam", "last_name": "Mickiewicz"}
        }
    )

def greetings(request, name=""):
    return HttpResponse("Hello" + " " + name)

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

# posts/
def listview(request):
    return render(
        request=request,
        template_name="posts/list.html"
    )

articles/templates/authors/details.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

{{ author.first_name }}

{% for article in author.articles.all %}
  {{ article.title }}
{% endfor %}

</body>
</html>

books/templates/books/details.html
{% extends 'base.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}

    <table class="table table-stripped">
        <tr>
            <th>Tytuł</th>
            <td>{{ book.title|title }}</td>

        </tr>
        <tr>
            <th>Slug</th>
            <td>{{ book.slug }}</td>
        </tr>
        <tr>
            <th>Autor</th>
            <td>{{ book.author|title }}</td>
        </tr>
        <tr>
            <th>Opis</th>
            <td>{{ book.description|truncatewords:50 }}</td>
        </tr>
        <tr>
            <th>Rok wadania</th>
            <td>{{ book.year }}</td>
        </tr>
        <tr>
            <th>Ilość stron</th>
            <td>{{ book.pages }}</td>
        </tr>

    </table>


{% endblock %}

books/templates/books/list.html
{% extends 'base.html' %}

{% block title %}Lista książek{% endblock %}

{% block content %}
<h1>Lista książek</h1>
    <ul>
    {% for book in books %}
        <li><a href="{% url 'books:details' forloop.counter  %}">{{ book.title|title }}</a></li>
    {% endfor %}
    </ul>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Page{% endblock %}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <style>
        .pochyly {
            font-style: oblique;
        }

    </style>
</head>
<body>
<div class="container">
{% include 'includes/header.html' %}

<p>paragraf</p>
<p class="pochyly">paragraf klasy pochyly</p>


{% block content %}
{% endblock %}

{% include 'includes/footer.html' %}
</div>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

templates/homepage.html
{% extends "base.html" %}
{% load boosk_extras %}

{% block title %}{{ block.super }} Main {% endblock %}

{% block content %}
    <h1>Homepage</h1>
    <p>Szablon z głównego templates - ustawionego w sekcji TEMPLATES.DIRS w settings</p>
    {{ dane }}

    {% for el in dane %} {# for to jest także `tag` #}
        <p>{{ el }}</p>
    {% endfor %}



    {{ 'jakis tekst'|upper }}
    <br>
    {{ 'Ala ma kota. kot ma Alę'|upper|truncatewords:"5" }}
        <br>
    {{ a_list|join:"-" }}

    <br>
    {{ value|default:"nothing" }}
    <br>
    {{ 2045 |filesizeformat }}

    {% comment %}

    To jest komentarz
    {% endcomment %}

    <br>
    {{ "Ala ma KOTA"|to_lower }}

    <br>
    {{ "Ala ma KOTA"|to_lower|cut:"ala" }}

    <br>
    {% current_time %}
    <br>
    {{ author }}

        {{ author.name }}
{% endblock %}

templates/includes/footer.html
<footer>Stopka strony poprawiony


    <ul>
        <li><a href="{% url 'homepage' %}">Brand</a></li>
        <li><a href="{% url 'posts:list' %}">Blog</a></li>
        <li><a href="{% url 'books:list' %}">Biblioteka</a></li>
    </ul>

</footer>

templates/includes/header.html
<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'homepage' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:list' %}">Posts</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'books:list' %}">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>

        <form class="d-flex" method="post">
            {% csrf_token %}
            <input class="form-control me-2" type="text" placeholder="Search" name="q">
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
    </div>
</nav>

templates/posts/list.html
{% extends 'base.html' %}

{% block title %}Lista postów{% endblock %}

{% block content %}
<h1>Lista postów</h1>
{% endblock %}